BaSP-a2022/ayom-a-trackgenix-server

src/data/admins.json

BaSP-TG-XX: Short description

---

src/data/admins.json
src/data/time-sheets.json
src/index.js
src/resources/time-sheets.js

Endpoints added: 
- /time-sheets/getAll
- /time-sheets/getById
- /time-sheets/editById
- /time-sheets/filterBy
Updated `time-sheets.json`

BaSP-TG: some /time-sheet endpoints added

---

src/data/super-admins.json
src/index.js
src/resources/super-admins.js

New routing in `index.js`: 
```
/super-admin/<endpoint>
```
New endpoints, in `super-admins.js`:
`[GET]` -> Returns an array of all registered super admins.
```
/super-admin/getAll
```
`[PUT]` -> Edit an super admin entry with valid id. Only defined properties in the request's body are updated.
```
/super-admin/editById
```
`[GET]` -> Returns an array of super admins that match with criteria sent in the request's query parameters object. 
```
/super-admin/filterBy
```
Valid filter query parameters:
- nameIs: returns super admins with the exact same `name` string
- nameContains: returns super admins whose `name` string contains the query param string.
- lastNameIs: returns super admins with the exact same `lastName` string
- lastNameContains: returns super admins whose `lastName` string …

BaSP-TG: Created /super-admin endpoint. Added editing and filtering functionality.

---

package-lock.json
package.json
postman_collection.json
src/index.js

JOI and Mongoose libraries installed.
Folders: /models, /controllers, /routes, /validations created with their corresponding files.
Postman collections created.
MongoDB connected.

BaSP-TG-03: Set up the environment

---

postman_collection.json
src/controllers/employee.js
src/index.js
src/models/Employee.js
src/routes/employee.js
src/routes/index.js
src/validations/employee.js

Endpoints:
- getEmployeeById -> Return the employee selected by ID.
- editEmployee -> Edit and update the employee selected.
- deleteEmployee -> Deletes a selected employee by ID.

BaSP-TG-13: Employee Endpoints (getEmployeeById, editEmployee, deleteEmployee)

---

postman_collection.json
src/controllers/superAdmin.js
src/index.js
src/models/SuperAdmin.js
src/routes/index.js
src/routes/superAdmin.js
src/validations/superAdmin.js

[GET] getAll: using the function find(), we can see all the super admin list.
[POST] create: using 'New' we can create a new super admin, only if the fields are filled in the body.

BaSP-TG-07:super-admin/endpoints/getAll-create

---

postman_collection.json
src/controllers/projects.js
src/index.js
src/models/Projects.js
src/routes/index.js
src/routes/projects.js
src/validations/projects.js

[GET] getAll: using the function find(), we can see all the projects list and we can filter by projects names.
[POST] create: using 'New' we can create a new project, only if the fields are filled correctly in the body.

BaSP-TG-16: Projects Endpoints (GetAll and Create)

---

postman_collection.json
src/controllers/admins.js
src/index.js
src/models/Admin.js
src/routes/admins.js
src/routes/index.js
src/validations/admins.js

- Create: creates an admin with the data completed in the body
- GetAll: shows a list of all the admins in the data base

BaSP-TG-06: Admin Endpoints (GetAll and Create)

---

Readme.md

Update description and members and add tech section

BaSP-TG-18: update README

---

src/controllers/task.js

Fixed filter and how error is managed on getAllTasks

BaSP-TG-38: Fixed getAllTasks

---

src/routes/task.js

The only change I needed to make was in task.js

BaSP-TG-21: Change all the routes

---

src/controllers/projects.js
src/models/Projects.js

- Throw added to project endpoints
- Populate added to controllers/projects
- Model Schema updated to have relationship

BaSP-TG-23: Update Projects Schemas and Controllers

---

postman_collection.json
src/controllers/projects.js
src/routes/projects.js

- Fixed and completed the Postman Collection
- Spelling mistake fixed on controllers/projects.js (founded with found)
- "Patch" method replaced with "Put" method.

BaSP-TG-40:  Fixed Postman Collection

---

package-lock.json
package.json
src/app.js

Install cors library and implement on the server.

BaSP-TG-48: Install cors library

---

src/controllers/projects.js

Modify populate in projects to get the complete employee in the employee property of projects

BaSP-TG-57: Modify populate in Project

---

src/controllers/admins.js
src/controllers/employee.js
src/controllers/projects.js
src/controllers/superAdmin.js
src/controllers/timeSheet.js

BaSP-TG-71: Fix get filter and create employee response

---

src/controllers/admins.js
src/controllers/employee.js
src/controllers/projects.js
src/controllers/superAdmin.js
src/controllers/timeSheet.js
src/tests/timesheets.test.js

- Fix editEmployee method in controllers/employees to return the correct message
- Fix typo error in timeSheets controller

BaSP-TG-55: fix editEmployee method

---

src/controllers/projects.js
src/tests/projects.test.js

- fix delete status response in Projects
- fix tests to accommodate new response status in Projects

BaSP-TG-72: Delete method returns unexpected status (Projects)

---

src/controllers/projects.js
src/controllers/timeSheet.js
src/index.js

-Added an error message when PUT method receives an invalid ID

TG-53: Projects bug fix

---

package-lock.json
package.json
src/constants/roles.js
src/controllers/admins.js
src/controllers/employee.js
src/controllers/superAdmin.js
src/helpers/firebase/index.js
src/middlewares/authMiddleware.js
src/models/Admin.js
src/models/Employee.js
src/models/SuperAdmin.js
src/routes/admins.js
src/routes/employee.js
src/routes/projects.js
src/routes/task.js
src/routes/timeSheets.js
src/tests/timesheets.test.js

- Install Firebase library
- Set .env
- Configure, initialize and export Firebase app
- Create middleware to check the Firebase user token and role
- Update controllers for all user types: create, update and delete requests
- Add role permissions to every request
QA: 
- Checkout master
- Update master  `git fetch && git pull origin master`
- Checkout to this branch ` git checkout feature/TG-116/implement-firebase-server` 
- Install the dependencies `npm i`
- Run in console `npm start`
- See the description in the PR of the ticket TG-115 to make the frontEnd side of the test

BaSP-TG-116: Implement firebase server

---

package.json
src/controllers/admins.js
src/controllers/employee.js
src/controllers/superAdmin.js
src/helpers/bcrypt/index.js

- Install bcrypt
- Add function to encrypt passwords

BaSP-TG-128: encrypt-passwords

---

src/controllers/admins.js
src/controllers/employee.js
src/controllers/superAdmin.js

- Fix passwords update send ecrypt to firebase.

BaSP-TG-151: Firebase password hotfix

---

src/controllers/admins.js
src/controllers/employee.js
src/controllers/projects.js
src/models/Admin.js
src/models/Employee.js
src/models/Projects.js

- add "isDeleted" field to models
- modify admins controller to new logic
- modify employees controller to new logic
- modify projects controller to new logic
How to test?
- with postman delete a admin, employee or project.
- the getAll method now will no longer show entitys with "isDeleted: true"
- after testing go to mongoDB and revert the changes to the isDeleted fields

BaSP-TG-140: Delete account employee

---

src/controllers/admins.js
src/controllers/employee.js
src/controllers/superAdmin.js
src/routes/admins.js
src/routes/employee.js
src/routes/superAdmin.js
src/validations/admins.js
src/validations/employee.js
src/validations/superAdmin.js

- Create update middleware for each entity.
- Update routes for each entity.
- Update controllers for each entity.

BaSP-TG-153: Update Profile Bug password BE

---

src/controllers/login.js
src/helpers/bcrypt/index.js
src/routes/admins.js
src/routes/index.js
src/routes/login.js

- Create new endpoint to login for QA
How test:
1. Open postman
2. Make new POST request to `[URL]:[PORT]/api/login` example `localhost:4000/api/login`
3. Add email and passwords in the headers
4. Await token response

BaSP-TG-158: Endpoint login token

---

package-lock.json
src/routes/projects.js

- add role employee to project put route

BaSP-TG-163: fix routes
